### ISSUE TITLE
Custom User Model related name

### ISSUE THREAD

**Issue by kodeine** [bennylope/django-organizations#100]
First of all thank you for this package.

I have a custom user model. How can i add a reverse relation to get the organization belonging to that user?

**Comment by bennylope** [comment]
The reverse relation name from user to organization should be the same regardless of what user model you use, `organization_set`, which is a `ManyRelatedManager` instance.

**Comment by kodeine** [comment]
@bennylope 
Thanks for your reply.

So this is what my custom user model looks like.

```python
from organizations.models import Organization
class Team(Organization):
    pass

class User(without(AbstractUser, 'email')):
    team = models.ForeignKey(Team, null=True, blank=True, related_name='team')

    address = models.ForeignKey(Address, null=True, blank=True, related_name='address')
    profile = models.ForeignKey(Profile, null=True, blank=True, related_name='profile')
    phones = models.ManyToManyField(Phone, related_name='phones')

    is_blocked = models.BooleanField(choices=((False, 'False'), (True, 'True')), default=False)
    is_volunteer = models.BooleanField(choices=((False, 'False'), (True, 'True')), default=False)
```
Do i have to define organization somewhere to be able to use `organization_set`?

**Comment by bennylope** [comment]
The reverse relationship from B->A is [added when a foreign key is created](https://docs.djangoproject.com/en/1.9/ref/models/relations/#django.db.models.fields.related.RelatedManager) from A->B. You get `organization_set` for free.

Because you're using [multi-table inheritance](https://docs.djangoproject.com/en/1.9/topics/db/models/#multi-table-inheritance) you do not get a reverse relationship from `User` to your customer organization, `Team`, only to the Organization model. Because multi-table inheritance is built on a foreign key itself, you can use the reverse relation from Organization to your custom organization model.

```python
>>> user.organization_set.all()[0].team
```

**Comment by kodeine** [comment]
@bennylope  Thanks :+1:

**Comment by kodeine** [comment]
So what if i use with OneToOneField... i can make a reverse relation but when a new organization is created it uses table `oragnizations_organization` so a new org is inserted in it and not in `team` table. So reverse relation does not work from user.team until i insert id of org manually.
```python
from organizations.models import Organization
class Team(Organization):
    description = models.TextField()

class User(without(AbstractUser, 'email')):
    team = models.OneToOneField(Team, null=True, blank=True, related_name='team')
```

**Comment by kodeine** [comment]
@bennylope Sorry im new to python/django so ignore my silly questions.

So i've made a model without a `team foriegnKey`. And `get_user_model().objects.organizations_organization` gives me the organizations attached to the user. Fair enough so far. How can i use a custom organization model so it supports organization image (thumbnail) field as well?

If i am going to be using like 
```python
from organizations.models import Organization
class Team(Organization):
    pass
```
How am i suppose to use `Team` class in User model?

**Comment by bennylope** [comment]
Sorry, your questions are decent questions, but they're beyond the scope of this package.
