### ISSUE TITLE
Limit users?

### ISSUE THREAD

**Issue by imaia** [bennylope/django-organizations#101]
It would be nice to be able to limit how many users an organization may have.

**Comment by bennylope** [comment]
There are a couple of ways this might be implemented, for example limiting a set number of users to any organization (site wide) or based on some other relation, like a subscription level. In either case you can benefit by using this package as the foundation and [adding your own organization](http://django-organizations.readthedocs.io/en/latest/custom_usage.html) that implements the limit.
