### ISSUE TITLE
Django REST

### ISSUE THREAD

**Issue by farice** [bennylope/django-organizations#102]
Hi there,

I'm interested in implementing django-organizations into my existing REST API. However, it appears django-organizations hasn't seen development in some time. 

I am curious if it would be compatible with Django 1.10 and Django REST 3.4.3? 

Thanks for your help.

Faris

**Comment by bennylope** [comment]
> I am curious if it would be compatible with Django 1.10 and Django REST 3.4.3?

Not just yet, I haven't had a chance to finish the 1.10 compatibility update. In a week or so it should be.

> However, it appears django-organizations hasn't seen development in some time.

Yep, development on this project is driven by project needs rather than development for the sake of development.

**Comment by bennylope** [comment]
Version 0.8.0 supports Django 1.10. I would expect no specific compatibility issues between Django Organizations and Django REST Framework.

**Comment by spoetnik** [comment]
How could I expose the `RegistrationBackend` and the `InvitationBackend` using Django REST Framework?
How could I serialize the backends??
