### ISSUE TITLE
Pre-existing users are not given notification when they are added to an organization

### ISSUE THREAD

**Issue by amadornimbis** [bennylope/django-organizations#114]
Currently, pre-existing users are not given sent an email notifying them when they are invited to, and thus automatically added to, an organization. The logic for this is in the line below:

https://github.com/bennylope/django-organizations/blob/dev/organizations/backends/defaults.py#L288

I am currently changing this behavior in a custom invitation backend by overriding this function, but I am curious if this would this be a feature you would be interested in adding if I make a pull request for it?

**Comment by bennylope** [comment]
Yeah, as long as there's some kind of sensible default that sounds good.

It might be good to break out the two different notifications so they're easier to override. But if you've already got the code a pull request is welcome!

If the backend functionality is sufficiently different than the default backend we could add as a new backed. The idea is that these can be overridden locally but there's also no reason why this project can't ship with multiple backends that do different things (provided they're fairly standard).
