### ISSUE TITLE
Unable to use Mixins with Django 1.10 and using django-organizaitons as a base package.

### ISSUE THREAD

**Issue by mwisner** [bennylope/django-organizations#116]
When attempting to use django-organizations as a "base package" described in the documentation here: http://django-organizations.readthedocs.io/en/latest/cookbook.html#advanced-customization, it doesn't appear that mixins are usable.

Perhaps I am just way off base here, and this isn't actually a bug, but I had thought that I would be able to simply replace the models with my own and then continue to use the mixes and other functionality provided by the django-organizations package. 

However, when attempting to do so in 1.10 I receive the following error:

```  RuntimeError: Model class organizations.models.Organization doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS. ```

Am I just using the package in correctly or is there some way to just replace the models and continue to use the additional functionality in some way?

Also, if this is a bug i'm definitely willing to try and help resolve it, just wanted to make it wasn't something I was obviously doing wrong. 

*Versions Installed*
Python: 2.7
Django: 1.10.4
Django-Organizations: 0.8.2

**Comment by bennylope** [comment]
Are you using those abstract base classes as the base class for your models or using them as mixins? A snippet from your code would help me understand what you're dealing with.

**Comment by mwisner** [comment]
Hi,

Here is some of the code i'm working on:

https://gist.github.com/mwisner/d0be2a254a4256467b4885c56bb1e9c6

Basically, by including the MembershipRequiredMixin in the endpoints.py (Specifically what i'm doing is working on exposing organization functionality via api/DRF.) It throws the error described above, Hover when the Mixin is not used it seems to work fine.

**Comment by bennylope** [comment]
Ah, got it - I wasn't thinking about the view mixins. Yes, this will be a problem. Right now these mixins are written with the _concrete_ `Organization`, et al., models in mind.

This isn't a bug, although it's not a good thing either. There hasn't been a real push to update this functionality to support custom models out of the box. Unfortunately you'll have to use your own mixins for the time being.
