### ISSUE TITLE
Content by group.

### ISSUE THREAD

**Issue by spoetnik** [bennylope/django-organizations#117]
Any suggestions on making content available to an organization, and only to that organization? Like content for a private group

**Comment by bennylope** [comment]
Sure! Instead of a lengthy response, see the [updated section in the docs](http://django-organizations.readthedocs.io/en/latest/cookbook.html#restricting-and-isolating-resources) on isolating content.

**Comment by spoetnik** [comment]
Thanks a lot!

**Comment by spoetnik** [comment]
@bennylope  Thanks for describing this functionality in the documentation.
Could you maybe implement this isolating of content in the example app?
I am having a hard time using the user object in a custom manager. A code example would be of great help I think.

**Comment by bennylope** [comment]
> Could you maybe implement this isolating of content in the example app?

I could, but this would be at the [very bottom](http://i2.cdn.cnn.com/cnnnext/dam/assets/130301151745-02-sinkholes-0301-horizontal-large-gallery.jpg) of my priority list.

This won't work:

```python
class MeetingMinutesQuerySet(models.query.QuerySet):
    
    def accountminutes(self):
        return self.filter(account__users=request.user)
```

You may have noticed in the interim that `request.user` is inaccessible to the method. You need to make the user a method argument and then pass it explicitly to the queryset method when you call it.
