### ISSUE TITLE
Single inheritance and DRYness

### ISSUE THREAD

**Issue by nemesisdesign** [bennylope/django-organizations#118]
I want to extend *django-organizations* base models but they are fairly limited compared to the concrete ones.

The concrete models provide interesting features that I'm satisfied with and I want to use, but I need to have my own models so I will need to duplicate some of the code of django-organizations to get what I want. I believe the logic in the concrete models could be made abstract too to avoid code duplication (like it was done with django's `AbstractUser`).

I've done something similar in two (very niche, networking related) apps I have been working latelly:

- [django-netjsonconfig](https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/models.py)
- [django-x509](https://github.com/openwisp/django-x509/blob/master/django_x509/models.py)

Those links link to the main model file of each app, you will notice the concrete models are VERY lean. 

The abstract ones contain all the logic, so third party apps can extend that logic without duplicating it.

At the moment I'm forced to duplicate some code of django-organizations in my own app, but I'd like not to. Would you be interested in a pull request that attempts to solve this problem? If you would, I'll work on it. I would prefer to not duplicate code right now because I know it will be a pain later to maintain.

**Comment by bennylope** [comment]
> Would you be interested in a pull request that attempts to solve this problem? If you would, I'll work on it.

That sounds great. Ensure its got some good tests around it so we can see that the functionality works with the concrete models here and user defined concrete models and this would be an fantastic improvement!

**Comment by nemesisdesign** [comment]
Awesome. I started working on it, it had been daunting initially because I have no experience in messing with metaclasses, but my intuition is that the new abstract classes will have to be named exactly as the actual base ones, just located elsewhere. I'll pay attention to backward compatibility first, and when things work out I'll add tests for the new functionality.

Once everything works out, we can look into style issues and naming.

I'll push changes to my fork referencing this issue.

**Comment by RobertChristopher** [comment]
Very nice implementation @nemesisdesign. Looks good to me. The decoupling between the abstract and base classes was a very good approach.

**Comment by nemesisdesign** [comment]
Thx @RobertChristopher, waiting for @bennylope now.

**Comment by nemesisdesign** [comment]
THX @bennylope for merging PR #119. Looking forward to see version 0.9.0 released on pypi.
