### ISSUE TITLE
Missing migration ?

### ISSUE THREAD

**Issue by zemanel** [bennylope/django-organizations#122]
I'm utilising latest version on my project and a migration is generated for organisations when i run migrate:

´´´
$ dcp run web python manage.py makemigrations
Migrations for 'organizations':
  /venv/lib/python3.5/site-packages/organizations/migrations/0002_auto_20170219_1936.py:
    - Alter field slug on organization
´´´

- django-organizations==0.9.0
- Django==1.10.5

**Comment by bennylope** [comment]
**_Thank you_** for identifying and sharing this. Fixed and out n PyPI.
