### ISSUE TITLE
Adding details to organizations

### ISSUE THREAD

**Issue by aphelionz** [bennylope/django-organizations#127]
Hi, here's my attempt at this by using a OneToOne model field. I'd love to hear your and the community's thoughts!

https://gist.github.com/aphelionz/6f43d3b804be0799a7f0e7af17d7698f

**Comment by bennylope** [comment]
That's certainly one way of adding this, very much akin to using a `UserProfile` model on a `User`. You could get a similar effect through multi-table inheritance, although the relationship is then implicit. Thanks for sharing this.

**Comment by aphelionz** [comment]
@bennylope link to something multi-table you're referring to?
