### ISSUE TITLE
UserAdminForm does not exist.

### ISSUE THREAD

**Issue by RichardProsser** [bennylope/django-organizations#128]
docs/cookbook.rst:
Showing the top two matches Last indexed on 17 Feb
    from .forms import UserAdminForm
    from .models import Account, AccountUser

    class AccountUserAdmin(admin.ModelAdmin):
        form = UserAdminForm()

    admin.site.unregister(Organization)
    admin.site.unregister(OrganizationUser)

**Comment by bennylope** [comment]
Closed with cf3ce558dfa9b31e95105d749b1225159d3532f8

The referenced class is not part of the Django Organizations codebase, it is an example from a hypothetical app in the cookbook.

**Comment by jancsarc** [comment]
@bennylope , is there an example of a UserAdminForm? The documentation goes from "Model admin definitions" (where it speaks about a UserAdminForm()) and then in the next sequential section it goes into "The admin form class" (which is actually AccountUserForm and is NOT the UserAdminForm). Just seems like an odd sequence as the Cooking with Django Organization page seems to be implying that it is going to give you step by step instruction on how to do something, then it doesn't.
