### ISSUE TITLE
Custom invitation backend for organization subclass

### ISSUE THREAD

**Issue by alexcwatt** [bennylope/django-organizations#131]
I am running Python 3.5.2 on Windows 10 with Django 1.11.1 and Django Organizations 0.9.0.

Instead of putting "organizations" as an INSTALLED_APP, I subclassed OrganizationBase, AbstractOrganizationUser, and AbstractOrganizationOwner. By subclassing, I was able to add some fields that deal with basic roles/permissions for organization users. In particular, some users who are not owners should be able to view all organization data, and others have to be granted access on a per-object basis.

That is all working fine, but when I went to use a custom backend for invitations to an organization, I got this error:

```
RuntimeError: Model class organizations.models.Organization doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

For reference, my backend looks like this:

```
from dataview.models import MyOrganizationModel
from organizations.backends.defaults import InvitationBackend

class MyOrganizationModelInvitations(InvitationBackend):
    def __init__(self):
        super().__init__(MyOrganizationModel)
```

And I'm using this for my URL's:

```
from dataview.backends import MyOrganizationModelInvitations

urlpatterns = [
    ...,
    url(r'^invitations/', include(MyOrganizationModelInvitations().get_urls())),
]
```

When I added "organizations" to INSTALLED_APPS, the error went away, but now it wants me to create migrations for the organizations tables that I am not using.

Is there a way around this?

**Comment by bennylope** [comment]
I didn't have the time to try reproducing in full, the updates in the latest release, [0.9.2](https://pypi.org/project/django-organizations/0.9.2/), _should_ resolve this issue. Please try using that version and let me know.

**Comment by alexcwatt** [comment]
@bennylope Thank you, this should be a lot cleaner! I'll try to give it a spin tomorrow.

**Comment by alexcwatt** [comment]
@bennylope It works beautifully. Thank you! 💯
