### ISSUE TITLE
Filtering objects associated with user's organization

### ISSUE THREAD

**Issue by justinmayer** [bennylope/django-organizations#137]
Say I have an app called `services` that has a `ServiceInstance` object with a foreign-key relationship to an organization. Here is `services/models.py`:

```
from django.contrib.postgres.fields import JSONField
from django.db import models
from organizations.models import Organization as Account


class Service(models.Model):
    name = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)


class ServiceInstance(models.Model):
    service = models.ForeignKey(Service, related_name='instances')
    account = models.ForeignKey(Account, related_name='instances')

    settings = JSONField(
        help_text="Service settings and configuration data",
        blank=True,
        null=True,
        default=dict,
        )
```

I want to add a list view for service instances, and that view should only include instances that are associated with the logged-in user's current organization. Here is `services/views.py`:

```
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from organizations.mixins import MembershipRequiredMixin

from .models import Service, ServiceInstance


class ServiceInstanceListView(LoginRequiredMixin, MembershipRequiredMixin, generic.ListView):
    model = ServiceInstance
    queryset = ServiceInstance.objects.filter(account=???)
```

I am still wrapping my mind around class-based views in general and using them with mixins in particular, so I can't quite figure out what I need to do in order to be able to filter the queryset to only include the objects associated with the current user's organization. Also, I am quite open to the possibility that I may be approaching this all wrong in the first place and am thus open to alternate ways of achieving the desired goal. 😄 

Any suggestions? Some guidance would be much appreciated. Once I have more info about this, I'll most likely add some associated pointers to the documentation.

**Comment by bennylope** [comment]
This is a good question about how Django class based views work.

The `queryset` class attribute you've defined here is a declarative definition and is necessarily consistent across requests. 😞 

However you can either amend it or ignore it (and thus not bother adding it) by defining your own [`get_queryset`](https://docs.djangoproject.com/en/1.11/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.get_queryset) method 😀 

At its simplest:

```
class ServiceInstanceListView(LoginRequiredMixin, MembershipRequiredMixin, generic.ListView):
    model = ServiceInstance
    queryset = ServiceInstance.objects.all()  # or some other filtered queryset 

    def get_queryset(self):
        return self.queryset.filter(account=self.organization)
```

Does that help?

FWIW the mixins are one area of the codebase that _work_ but haven't gotten the updates I'd like them to yet (including documentation and extensibility).

**Comment by justinmayer** [comment]
It does help, thank you. When I tried that, I got a "No Organization matches the given query" response, which probably isn't surprising as I don't believe the [OrganizationMixin](https://github.com/bennylope/django-organizations/blob/dev/organizations/mixins.py#L34) is necessarily paying attention to the currently-logged-in user. Assuming for the moment (and for simplicity) that a user is only associated with a single organization, do you have any suggestions as to how I would modify this code to only show the objects associated with the currently-logged-in user's organization? Or am I missing something?

By the way, thank you *so* much for always responding so quickly and attentively, despite your many other obligations. As an open source maintainer [myself](https://github.com/getpelican/pelican), I know too well how challenging it can be to find time for it. Your guidance is truly and greatly appreciated!

**Comment by bennylope** [comment]
> Assuming for the moment (and for simplicity) that a user is only associated with a single organization, do you have any suggestions as to how I would modify this code to only show the objects associated with the currently-logged-in user's organization? Or am I missing something?

I'm sure there's a better way with Django's reverse relationships, but:

```org = Organization.objects.filter(users=request.user).first()```

> By the way, thank you so much for always responding so quickly and attentively, despite your many other obligations. 

You're welcome! The detailed and clearly written issues/PRs make it easy for me.
