### ISSUE TITLE
HttpResponseBadRequest isn't an exception

### ISSUE THREAD

**Issue by LegoStormtroopr** [bennylope/django-organizations#141]
If you try to remind a user of their invitation after they've already joined, the page throws a 500.

https://github.com/bennylope/django-organizations/blob/1e3bbd971902b854c4d4f14d49f58f5f2d31eda9/organizations/views.py#L145

```
File "/home/ubuntu/.virtualenvs/aardvark/lib/python3.4/site-packages/organizations/mixins.py" in dispatch
  112.                 **kwargs)

File "/home/ubuntu/.virtualenvs/aardvark/lib/python3.4/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/home/ubuntu/.virtualenvs/aardvark/lib/python3.4/site-packages/django/views/generic/detail.py" in get
  115.         self.object = self.get_object()

File "/home/ubuntu/.virtualenvs/aardvark/lib/python3.4/site-packages/organizations/views.py" in get_object
  145.             raise HttpResponseBadRequest(_("User is already active"))

Exception Type: TypeError at /registry/orgs/42/people/440/remind/
Exception Value: exceptions must derive from BaseException
```

This is because `HttpResponseBadRequest` isn't an exception and can't be thrown (in Python 3 at least). Perhaps a raise Http404 is better?

Happy to submit a PR

**Comment by bennylope** [comment]
> This is because `HttpResponseBadRequest` isn't an exception and can't be thrown (in Python 3 at least). Perhaps a raise Http404 is better?

Oof, yeah, that plus a logging statement about why it's missing would be much a better.

> Happy to submit a PR

PR welcome!

**Comment by ScottHull** [comment]
I've come here to report this bug as well.

**Comment by bennylope** [comment]
Thanks the reminder. Out in 1.1.2.
