### ISSUE TITLE
Error migrating custom model

### ISSUE THREAD

**Issue by joshlsullivan** [bennylope/django-organizations#150]
I'm writing a new organization model and get the following error:

`django.db.migrations.exceptions.NodeNotFoundError: Migration vend.0001_initial dependencies reference nonexistent parent node ('organizations', '0003_auto_20180409_0308')`

Any ideas? 

When I run makemigrations, I do get this:

```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, organizations, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Migrations for 'organizations':
  /usr/local/lib/python3.6/site-packages/organizations/migrations/0003_auto_20180409_0308.py
    - Alter field slug on organization
```

That repeats over and over.

**Comment by bennylope** [comment]
Closed in https://github.com/bennylope/django-organizations/releases/tag/1.1.0
