### ISSUE TITLE
Can I add django-organizations to a Rest API project?

### ISSUE THREAD

**Issue by Red3nzo** [bennylope/django-organizations#155]
It seems that django-organizations can only work with websites and forms is there a way that I can include this in my rest api?

**Comment by bennylope** [comment]
> Can I add django-organizations to a Rest API project?

Yes!

This is just another Django app, so you can include it regardless of how you're rendering data on your site. If you're concerned about limited access to organizations or organization-related resources/objects, there's no Out Of The Box ™️ DRF support (for now at least) but you could reference the mixins as necessary to update the [querysets](http://www.django-rest-framework.org/api-guide/generic-views/#get_querysetself) in your Django REST Framework views.
