### ISSUE TITLE
[Question] Is it possible to have multiple owners or different roles?

### ISSUE THREAD

**Issue by LegoStormtroopr** [bennylope/django-organizations#158]
I'm keen to be able to have multiple owners of an organisation, but can't figure out if this is possible.

Also I've read over the docs and can't seem to find details on roles within organisations?

**Comment by bennylope** [comment]
Short answer: an organization cannot have multiple owners (at least within the context of the django-organizations modeled data structures, that is. If you want to add roles (which gives you a way out of having only one owner, more or less), then you want to make use of the [abstract models](http://www.django-organizations.com/en/latest/cookbook.html#advanced-customization-using-abstract-models), which will let you add fields to these models.

**Comment by LegoStormtroopr** [comment]
Thanks for the info!
