### ISSUE TITLE
Filtering OrganizationUser's by Organization

### ISSUE THREAD

**Issue by crystalfiction** [bennylope/django-organizations#167]
There is a relatively similar thread on this topic, but I can't seem to figure out how to translate it to my situation. I have a roster that I need to only display the organizationusers within the same organization of the viewer. I have a webapp that I am developing that is used to manage volunteers in an organization. This package is perfect for what I need, but I'm still new to backend development so I'm having trouble problem solving.

This is the code for the table view using Django_Tables2 package:
```
#tables.py
class VolunteerTable(tables.Table):
    class Meta:
        model = OrganizationUser

# views.py
def VolunteerRoster(request):
    table = tables.VolunteerTable(OrganizationUser.objects.all())
    return render(request, 'staff/roster.html', {'table': table})
```
I'm trying to figure out how to either convert the view to a class-based view so I can use the OrganizationMixin and the SingleTableView in Django_Tables2's documentation.

I was thinking about something like this based on the other threads explanation
```
class VolunteerRoster(SingleTableView, OrganizationMixin):
    table_class = VolunteerTable
    queryset = OrganizationUser.objects.all()
    template_name = "staff_roster.html"

    def get_queryset(self):
        return self.queryset.filter(organization=self.get_organization())
```

When I try this I get: "TypeError: __init__() takes 1 positional argument but 2 were given"

As I said, I'm still new to django so I'm not really sure what to fix in this instance.

**Comment by bennylope** [comment]
Howdy! After a brief foray into the `Django_Tables2` docs, I think much of what you're trying to solve for is specific to that package.

Which is to say I'd like to help here, but I don't think it's really in the scope of _this_ package.

Your last example looks good, so without a stacktrace it's hard to know what the problem is... have you tried changing the order of parent classes (which affects what's called the [MRO](https://www.python.org/download/releases/2.3/mro/))?

Otherwise if you have a full stacktrace that would help.

**Comment by crystalfiction** [comment]
Thanks for the response! I wasn't sure if you would answer.

Would it be possible to just remove django_tables2 and use a regular html table with django-templates tags? In theory wouldn't this be possible with the organiations functionality?

**Comment by bennylope** [comment]
The short answer (two months later - sorry!) is that you don't need a special library to list organizations and their users. Front end libraries may be helpful for rendering sortable or filterable tables, but for the data itself I don't think you need such a library.
