### ISSUE TITLE
Structural permissions

### ISSUE THREAD

**Issue by MAkcanca** [bennylope/django-organizations#169]
Note: This is not a feature request nor an issue. I simply couldn't grasp my head around it and felt like I need to ask. 

I'm trying to build a system where scenario goes like this:
The superuser belongs to a root/main organization. Superuser creates a sub-organization and assigns some users to it. One of the users has admin rights and can create sub-organization under the sub-organization(sub-sub). And tree goes on like this. 
Example:

MainOrganization
- SubOrganization-1
- - SubOrganization-2
- - SubOrganization-3
- Suborganization-4
- Suborganization-5

In the end, SubOrganization-1 users can access all of the resources defined in SubOrganization-2 and SubOrganization-3.

Is this feasible? Are there any ways to accomplish this in a better way? I tried creating a Organization derived class which has a foreign-key of Organization but it doesn't feel right to do it in this structure.
```
class Client(Organization):
    main_organization = models.ForeignKey(Organization,
                                          related_name="clients", on_delete=models.CASCADE)
```
If this is too complicated to work with, we can just skip the "non-superuser" being able to create new organizations and assume it just can add users.

Thanks a lot.

**Comment by bennylope** [comment]
The short answer is that this is feasible.

You'll definitely want to use the abstract models, if not the meta base models for fully custom models, and I'd use a tree model as well, like MPTT. This way your organization model inherits from both, e.g.

```python
class MyOrg(MPTTModel, AbstractOrganization):
     # everything else here!
```

If you're not familiar with django-mptt I'd recommend [checking out the docs](https://django-mptt.readthedocs.io/en/latest/overview.html). It has features for managing tree relationships including efficiently tracking whether one _thing_ (e.g. a page) is in the subtree of another, or vice versa.

Your permissions would then need to check to see if the user is a member of an organization at the requisite level.
