### ISSUE TITLE
Registration/Invitation backend not sending emails

### ISSUE THREAD

**Issue by bharatnc** [bennylope/django-organizations#171]
Hi there!

I have implemented my own backend for Invitation and Registration using Base backends from Django Organization. 

I have included the smtp settings like mail server, port etc in my settings file. I realized that no emails are sent during Organization, User creation etc and I don't know if something else needs to be configured to make this work 

It would be really helpful to know if I need to add something additional / any recommendations. Thanks!

**Comment by bennylope** [comment]
>  I realized that no emails are sent during Organization, User creation etc and I don't know if something else needs to be configured to make this work

That _sounds_ like something the invitation backends don't handle. Can you describe the workflow in which you would expect someone to receive an email?

**Comment by bharatnc** [comment]
> > I realized that no emails are sent during Organization, User creation etc and I don't know if something else needs to be configured to make this work
> 
> That _sounds_ like something the invitation backends don't handle. Can you describe the workflow in which you would expect someone to receive an email?

Thanks @bennylope, when we add an user to an organization who is not part of it, but is already an user in the `accounts_user` table, I expect the invitation backend,[ `invite_by_email`](https://github.com/bennylope/django-organizations/blob/master/organizations/backends/defaults.py#L331) function to trigger an email invitation to the user (given that I have already set up the necessary django email config in the `settings.py` file.)

Similar behavior is expected for the registration backend, [`register_by_email`](https://github.com/bennylope/django-organizations/blob/master/organizations/backends/defaults.py#L233) function.

I managed to write my own backend which handles the `email` handling part of it by using the abstract invitation and registration backends, but still, is there a better way to do this?

**Comment by bharatnc** [comment]
@bennylope  closing this out for now. I think I have got I wanted. Thanks!
