### ISSUE TITLE
Update PyPI releases?

### ISSUE THREAD

**Issue by bashu** [bennylope/django-organizations#174]
Hey @bennylope !

Can you please upload 2.0.0a* versions on pypi or tag them correctly?

**Comment by bennylope** [comment]
> Can you please upload 2.0.0a* versions on pypi

Please see [the release history](https://pypi.org/project/django-organizations/#history)!

> or tag them correctly?

????

**Comment by bashu** [comment]
> Please see [the release history](https://pypi.org/project/django-organizations/#history)!

where is 2.x?

![screenshot 2019-02-15 08 41 15](https://user-images.githubusercontent.com/144783/52828986-95d2f380-30fd-11e9-9f8a-31d96ba8638a.png)

**Comment by bennylope** [comment]
The release history on PyPI. That will show you the pre-release versions which have been published to PyPI.
