### ISSUE TITLE
token validation of  a new user (user registration backend) always fails.

### ISSUE THREAD

**Issue by bharatnc** [bennylope/django-organizations#176]
Hi @bennylope ,

I realize that a random password is set, when creating a user in the registration backend.
https://github.com/bennylope/django-organizations/blob/master/organizations/backends/defaults.py#L348-L352

Would it make sense to forge a proper user token during the time of creation of the user - since the `activate_view` in the BaseBackend checks to see if the forged token is a valid token?

https://github.com/bennylope/django-organizations/blob/master/organizations/backends/defaults.py#L134

Right now the validate_token func doesn't work as the token forged isn't a proper one (random one).

If this sounds ideal (I might be wrong) , I can submit in a PR, since this is something that I would myself need.

**Comment by bennylope** [comment]
If you have a PR for this that'd be welcome.

In version 2, in pre-release, an updated system does away with the need to use these tokens, using an intermediate model instead with a UUID.
