### ISSUE TITLE
Could you please give me a instance?

### ISSUE THREAD

**Issue by Chise1** [bennylope/django-organizations#180]

**Comment by bennylope** [comment]
Sorry, I don't know what you're asking! Can you elaborate?

**Comment by Chise1** [comment]
I'd like to see a little more of django-organizations, and I hope you provide a good example for reference.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Ben Lopatin <notifications@github.com>
发送时间: Tuesday, July 9, 2019 1:25:34 AM
收件人: bennylope/django-organizations
抄送: Chise1; Author
主题: Re: [bennylope/django-organizations] Could you please give me a instance? (#180)


Sorry, I don't know what you're asking! Can you elaborate?

―

**Comment by dzungrevo** [comment]
Hi @bennylope ,

I'm trying to run example on your git repos, but cant get it run normaly. This logs is what i've got when runserver:

> ERRORS:
accounts.AccountUser: (models.E012) 'unique_together' refers to the non-existent field 'organization'.
accounts.AccountUser: (models.E012) 'unique_together' refers to the non-existent field 'user'.
accounts.AccountUser: (models.E015) 'ordering' refers to the non-existent field 'organization'.
accounts.AccountUser: (models.E015) 'ordering' refers to the non-existent field 'user'.
vendors.VendorUser: (models.E012) 'unique_together' refers to the non-existent field 'organization'.
vendors.VendorUser: (models.E012) 'unique_together' refers to the non-existent field 'user'.
vendors.VendorUser: (models.E015) 'ordering' refers to the non-existent field 'organization'.
vendors.VendorUser: (models.E015) 'ordering' refers to the non-existent field 'user'.

System check identified 8 issues (0 silenced).

(Using Django 2.1 and Python 3.6)

I've same request as Chise1, could you provide us a good example (a little more detail) for reference?

Many Thanks,
