### ISSUE TITLE
cannot import name 'AbstractOrganizationInvitation' from 'organizations.abstract'

### ISSUE THREAD

**Issue by erikvlm** [bennylope/django-organizations#194]
Trying to create my own organization model and I'm receiving the following error when saving/doing the migrations 

`ImportError: cannot import name 'AbstractOrganizationInvitation' from 'organizations.abstract'`

```
from organizations.abstract import (
    AbstractOrganization,
    AbstractOrganizationInvitation,
    AbstractOrganizationOwner,
    AbstractOrganizationUser,
)
```

**Comment by juuisle** [comment]
Which version of django-organizations are you using? Try to re-install the latest version.

**Comment by bennylope** [comment]
Going to close this as it doesn't seem reproduced anywhere and no follow up.
