### ISSUE TITLE
How this project can be used with RBAC ?

### ISSUE THREAD

**Issue by shirishbhalekar** [bennylope/django-organizations#218]
I Want to create oragnisation and having its admin and other users which will give specific roles.

**Comment by bennylope** [comment]
If you are using custom models (https://django-organizations.readthedocs.io/en/latest/cookbook.html#advanced-customization-using-abstract-models) then you can create a role filed like `user_type` in that code example. For better or worse there is no access control provided for that role out of the box here though.

Does that answer your question?
