### ISSUE TITLE
Necessity of OrganizationOwner?

### ISSUE THREAD

**Issue by dwasyl** [bennylope/django-organizations#226]
Hi all,

Just had a question for regular maintainers/users of `django-organization` regarding `OrganizationOwner`s. If the relationship is onl ya single owner per `Organization`, is it necessary to have a separate object for the owner relationship? Would an `owner` field (as a FK to a `OrganizationUser`) on `Organization` not accomplish roughly the same thing?

Just getting my head around the structure so appreciate any thoughts!

Cheers

**Comment by bennylope** [comment]
One motivator for using a separate model is that this is a separate relationship to model and not just an "attribute" of the organization.

A more urgent reason, if memory serves correctly, is the cyclic relationship in the database between the organization and organization users table. This does work! But I _think_ Django's migrations didn't handle this before (???).
