### ISSUE TITLE
Support for Django 4.0.1

### ISSUE THREAD

**Issue by obvionaoe** [bennylope/django-organizations#227]
Hi, does this package support the latest version of Django?

Thanks

**Comment by bennylope** [comment]
Yep https://github.com/bennylope/django-organizations/blob/86c386568b0b49a70273d9ab5a2f9d7f61b484c1/tox.ini#L6

**Comment by obvionaoe** [comment]
as a side note, is django-organizations compatible with [djangorestframework-simplejwt](https://github.com/jazzband/djangorestframework-simplejwt)?

**Comment by bennylope** [comment]
The short answer is "yes".

The long answer is "should be b/c they don't have overlapping functionality.

**Comment by obvionaoe** [comment]
Thanks
