### ISSUE TITLE
Would you still consider this package a good choice despite the low activiy here?

### ISSUE THREAD

**Issue by tommueller** [bennylope/django-organizations#248]
Hi,

looking for an honest opinion from some project members. I am seeking an organization management package for Django. As far as my research today went, I only found this single one here. It covers 95% of our requirements, but repo activity and community activity seems to be very low.

Is this just working and stable and all the ToDo's in the Wiki will not be done, but the repo is still actively maintained? Or should I rather invest into developing this ourselves, since nothing is happening here anymore?

Thanks!
Tom

**Comment by bennylope** [comment]
Moved to discussion #249
