### ISSUE TITLE
Re-do the twine upload because the classifiers are not showing on pypi

### ISSUE THREAD

**Issue by simkimsia** [bennylope/django-organizations#253]
when the version was 2.0.0, the classifiers did not show up

In the alpha version before 2.0.0
![CleanShot 2023-09-05 at 16 34 29@2x](https://github.com/bennylope/django-organizations/assets/245021/8c5125a3-4cc7-44af-a56b-ebe42938949a)

In the 2.0.0
![CleanShot 2023-09-05 at 16 35 14@2x](https://github.com/bennylope/django-organizations/assets/245021/b2d7faf5-b3c5-4d31-b532-38da855df4b8)

Probably need to recreate the package and upload it since the setup.cfg looks correct.

```
# Create the package
python setup.py sdist bdist_wheel

# Upload it to PyPI
twine upload dist/*
```

**Comment by bennylope** [comment]
Closed by #254!
