### ISSUE TITLE
Release `2.4.0` to `pypi`?

### ISSUE THREAD

**Issue by mgrdcm** [bennylope/django-organizations#268]
Greetings!  Looks like [`2.4.0` has a GH "release"](https://github.com/bennylope/django-organizations/releases/tag/2.4.0) but it isn't up on `pypi` yet: https://pypi.org/project/django-organizations/

Anything I can do to help get that onto `pypi`?  Thanks!

**Comment by mgrdcm** [comment]
Oh!  Looks like it *should* have been deployed but the publishing step failed: https://github.com/bennylope/django-organizations/actions/runs/8222770272

**Comment by mgrdcm** [comment]
Weird, even after #271 it's not showing up on `pypi`: https://pypi.org/project/django-organizations/

**Comment by bennylope** [comment]
That particular run did build, but that's all it did b/c it further checks for the creation of a "proper" GitHub release first, and that's what I hadn't created here!

Thanks for the gentle pokes to get this up there.

**Comment by mgrdcm** [comment]
You're welcome @bennylope and thanks so much for creating/maintaining this package!
