### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by shaneharter** [bennylope/django-organizations#64]
Hey Benny, 

Thanks for all your work on this. I started integrating it into my project today and I wanted to give you some feedback: 

1. On your git readme, it's confusing where you basically say "run pip install and then run setup.py". I couldn't figure out why you wanted me to do that. And of course, when i pip install it, it installs in a virtualenv site-packages dir that I have to go look for. 

2. It's not clear that I must install django_extensions or provide an alternative slug field, etc. I can see where you say I have the option of specifying an alternative but I didn't realize it was mandatory until I deciphered the error: Your SlugField class, django_extensions.db.fields.AutoSlugField, is improperly defined

Shane

**Comment by bennylope** [comment]
Thanks @shaneharter - let me know if you have any other trouble getting it working in your project.

**Comment by libovness** [comment]
+1 to @shaneharter's second point

**Comment by mutkoh** [comment]
@bennylope I'm also having @shaneharter second issue
