### ISSUE TITLE
no such table: organizations_organization

### ISSUE THREAD

**Issue by iraycd** [bennylope/django-organizations#68]
This is the common error after customization.

**Comment by bennylope** [comment]
Going to need more information than this. How are you installing this? What are you customizing? Are you trying to add custom models using single table inheritance or multi table inheritance? Do you have a traceback?

**Comment by bennylope** [comment]
If this isn't the same issue as #69 will reopen, but without additional information will assume so and that it's solved by 0.5.2 now.
