### ISSUE TITLE
Django 1.7+ migrations not included in pypi distribution

### ISSUE THREAD

**Issue by stevenmcdonald** [bennylope/django-organizations#69]
I tried installing both 0.5.0 and 0.5.1 via pip, and neither one seems to include django 1.7+ migrations. 

Poking around, it seems the migrations folder is present in the 0.5.0 zip and tars available from the GitHub releases tab, but the tar available from pypi does not include them (https://pypi.python.org/pypi/django-organizations#downloads)

**Comment by bennylope** [comment]
Thanks for catching this - still upgrading prod sites to Django 1.8 so haven't noticed. The 0.5.2 version is on PyPI with verified migrations module in the source distribution.
