### ISSUE TITLE
Feature: invite existing users

### ISSUE THREAD

**Issue by electroniceagle** [bennylope/django-organizations#71]
Is it possible to invite existing users to another organization?  We have a use case where a customer might need to belong to multiple organizations.  We're debating the approach of multiple separate User logins per customer versus giving customers membership in multiple organizations github-style.  The first approach appears to be the intended use, but it looks like it would be possible to write a backend that invited existing users without creating a new User account.  Just starting to look at the code in detail, but was wondering if anyone had already gone down this path.

**Comment by bennylope** [comment]
> Is it possible to invite existing users to another organization?

Yes. And in fact that's how every app I've used this project with works. User profiles and authentication can be entirely distinct from whatever kind of 'account' your site or app uses.

Typically you'll need to write a simple [invitation backend](http://django-organizations.readthedocs.org/en/latest/custom_usage.html#user-registration-and-invitations) extension with a few workflow customizations (e.g. notify the user that they're now a member of another account, or not).
