### ISSUE TITLE
custom AUTH_USER_MODEL

### ISSUE THREAD

**Issue by Guest007** [bennylope/django-organizations#83]
Hi
Python 3.5
Django 1.9b1
Linux

django-organizations - current from github

I'll try to use django-authtools (as email-only authorisation).
Default invite_by_email not working due to always try to directly get username (no such field), writing username, try to use first_name and last_name during making email...

**Comment by bennylope** [comment]
If the default `invite_by_email` isn't working the immediate answer is to [extend the backend class with a custom invitation backend](http://django-organizations.readthedocs.org/en/latest/reference/backends.html?highlight=invite_by_email).
