### ISSUE TITLE
released version is missing makemigrations changes

### ISSUE THREAD

**Issue by manelclos** [bennylope/django-organizations#84]
Hi,

As my Client class inherits from Organization, the initial migration will depen on a new created migration which is not going to be available (it was just created, locally):

Migrations for 'organizations':
  0002_auto_20151112_1643.py:
    - Alter field created on organization
    - Alter field modified on organization
    - Alter field created on organizationowner
    - Alter field modified on organizationowner
    - Alter field created on organizationuser
    - Alter field modified on organizationuser

Would you mind fixing the missing migration and releasing again? this is critical for making it work correctly. Thanks!

**Comment by avelis** [comment]
It looks like the commit @ 150299f440d3ec7e52b8893a64e36827511df0af contains the migration file in question. This would seem to be prompted when the project upgraded their version of django-extensions for testing.

At this point we would only need another release. Or if you are in a hurry you could install a version from 150299f440d3ec7e52b8893a64e36827511df0af or later.

**Comment by manelclos** [comment]
Hi Avelis, a new release would be great! Thanks!

**Comment by bennylope** [comment]
I can try pulling that commit out into the master branch, but unfortunately that's on the dev branch which is much farther ahead and not ready for release.

**Comment by avelis** [comment]
@bennylope hmm I understand now the branch issue. I didn't make the connection at first...

**Comment by bennylope** [comment]
Going to close this as the issue should be wrapped into #87

**Comment by bennylope** [comment]
The fix deployed in 4efb7fcf84f9bdd7fb0db9fe76fecd3cff168f3d is going to result in what was considered a "ghost" migration under South.
