### ISSUE TITLE
RemovedInDjango19Warning: Model class organizations.models.Organization doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by fablet** [bennylope/django-organizations#85]
I am using your app as a library, per the documentation, to great effect. Thank you.  I noticed that the other two deprecation warning that I am seeing were already declared and fixed in prior issues.
However, I think the warning below is showing up only when using your app as a library rather than an installed app.  So I thought you should know.

RemovedInDjango19Warning: Model class organizations.models.Organization doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  model = super(OrgMeta, cls).**new**(cls, name, bases, attrs)

**Comment by bennylope** [comment]
Thanks @fablet - are you using 0.5.3 with Django 1.8.x? I'll take a look - I'm actually using 0.5.3 myself as a non-installed library with Django 1.9rc1 and not noticing any issues (so far). Will keep an eye out for this though.

**Comment by fablet** [comment]
@bennylope - yes I am using 0.5.3 and Django 1.8.x  
The deprecation warning doesn't come up all of the time.  I thought it was happening when my mixin calls account.is_member(user) but it doesn't seem to be happening every time with that either. 
I will have to keep an eye out for exactly what is flagging the warning, and report back when I track it down.
