### ISSUE TITLE
Using non-django-extensions models causes migrations to fail

### ISSUE THREAD

**Issue by clokep** [bennylope/django-organizations#87]
The built in migrations requires the use of the the slugfield/timestamped field from django-extensions. Using the field types from Django Autoslug and Django model utils fails when running make migrations, e.g. using the following settings breaks `makemigrations`:

```python
ORGS_SLUGFIELD = 'autoslug.fields.AutoSlugField'
ORGS_TIMESTAMPED_MODEL = 'model_utils.models.TimeStampedModel'
```

You can see that running `makemigrations` attempts to create a migration. I'd expect it to respond `No changes detected`.
```
(_venv)vagrant@dev:/vagrant$ python manage.py makemigrations --dry-run
Migrations for 'organizations':
  0003_auto_20160104_2000.py:
    - Alter field created on organization
    - Alter field modified on organization
    - Alter field slug on organization
    - Alter field created on organizationowner
    - Alter field modified on organizationowner
    - Alter field created on organizationuser
    - Alter field modified on organizationuser
```

The workaround seems to be to just use the field classes from django-extensions. Note that you can see `django_extensions` used directly in both migrations:
* [0001_initial](https://github.com/bennylope/django-organizations/blob/fb56270afab4a8b7471095c308bfc3f3c2d8d9f9/organizations/migrations/0001_initial.py#L40-L41)
* [0002_auto_20151005_1823](https://github.com/bennylope/django-organizations/blob/fb56270afab4a8b7471095c308bfc3f3c2d8d9f9/organizations/migrations/0002_auto_20151005_1823.py#L18)

**Comment by clokep** [comment]
Thanks for fixing this so quickly!

**Comment by bennylope** [comment]
I'm planning on release a fix with this, let me know if it works for you.

**Comment by bennylope** [comment]
Also, thanks for reporting the issue! A related issue had already been reported but seeing this particular case helped clear it up very quickly for me.
