### ISSUE TITLE
Owner can't modify the organization.

### ISSUE THREAD

**Issue by curioswati** [bennylope/django-organizations#97]
In the organization create form, when the organization is created, the user is being assigned the owner. But when that user tries to edit the organization, it is redirected to a page saying, "admins only". So can the owner by default not edit the organization it created?

**Comment by bennylope** [comment]
Sounds like the backend is creating the user without setting the admin property on the `OrganizationUser`. Are you using your own invitation backend class or using the default?

**Comment by curioswati** [comment]
I am using default. Although I over rode the view for it. But I think it should be present in default one.

**Comment by yitjob** [comment]
I was about to ask the same.
Perhaps here: https://github.com/bennylope/django-organizations/blob/dev/organizations/forms.py#L109 the parameter is_admin should be set to True?

**Comment by curioswati** [comment]
I think here:
https://github.com/bennylope/django-organizations/blob/dev/organizations/utils.py#L58.

**Comment by bennylope** [comment]
Thanks for so carefully reporting this. Tested and closed in the latest release.
