### ISSUE TITLE
Redirection problem after clicking the invitation link

### ISSUE THREAD

**Issue by yitjob** [bennylope/django-organizations#98]
Hi, I am having this issue in Django 1.8.11:
When the invited user receives the invitation email and clicks the corresponding link, he is redirected to the login url.

The only way the user is properly set up is being logged on with any user account, being the inviter or another one, in which case the user is presented with the form.

Note: In neither cases the invited user is able to fill his UserRegistrationForm.

I couldn't find if this behavior is by design and I believe that perhaps is a bug.

Thank you.
Regards,

**Comment by yitjob** [comment]
It was because of 'authentication.middleware.login_required_middleware.LoginRequiredMiddleware'.

However in order to test allow the ^invite url to be login exempt I needed to copy the urlpattern to my project settings.

This is ugly, but it's another topic.

**Comment by bennylope** [comment]
Just to clarify, the problem was that you had middleware installed that requires authentication for all URLs by default?

**Comment by yitjob** [comment]
Yes. 
Perhaps the fact that prevents a new user from being registered is worth to be mentioned in the docs.
